# Generated by Django 4.1.7 on 2023-04-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPT_Table',
            fields=[
                ('dept_no', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EMP_Table',
            fields=[
                ('empno', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('mgr', models.IntegerField(max_length=100)),
                ('hiredate', models.DateField()),
                ('sal', models.IntegerField(max_length=100)),
                ('comm', models.IntegerField(max_length=100)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept_table')),
            ],
        ),
    ]
