# Generated by Django 4.1.7 on 2023-04-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_table',
            name='comm',
            field=models.IntegerField(null=True),
        ),
    ]
