# Generated by Django 4.1.7 on 2023-04-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_emp_table_empno_alter_emp_table_mgr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_table',
            name='dept_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
